# Site settings
title: KaraMudie
description: "Photo Journal"
url: "https://wildaye.github.io"
baseurl: "/karamudie.co.uk"
facebook_username: "KaraMudiePhotography"
instagram_username: "karmupix"
# email: "kara@karamudie.co.uk"
# twitter_username: "karmupix"
# github_username:  "wildaye"
# deviantart_username: ""
# flickr_username: ""
share: true

# Owner/author information
owner:
  name:   Kara Hood
  avatar: avatar.png
  favicon: favicon.ico
  info: Photographer

# Internal nav
nav:
  - HOME: "/karamudie.co.uk/"
  - GALLERY: "/karamudie.co.uk/gallery/"  
  - JOURNAL: "/karamudie.co.uk/journal/"
  - ABOUT: "/karamudie.co.uk/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination: ./_site
port: 4000


# Build settings
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
plugins:
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
